name: First workflow

on: push

jobs:
  hello:
    runs-on: ubnuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print Hello
        run: echo "Hello from GHA"
